### ISSUE TITLE
systemd service file example for start|reload|stop envoy

### ISSUE THREAD

**Issue by nskalis** [tetratelabs/getenvoy.io#100]
**What is incorrect, confusing or missing:**

What I find to be missing is an example systemd service file for the common ops of administrating envoy, such as start, stop, reload.
That would be of great help for an envoy newbie such as myself and others I assume.

**Suggested fix:**

Following our conversation in Slack, would you be so kind to document an example of
a systemd service file for starting, reloading, stopping envoy when installed using get envoy.io ?

**Comment by nskalis** [comment]
just a kind reminder on this please :) I would appreciate your help into closing this by providing the systems service file even as an example in this issue.

**Comment by lizan** [comment]
@nskalis A very quick sample based on upstream hot-restarter wrapper will be like:

```
[Unit]
Description=Envoy Proxy
Requires=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/envoy-hot-restarter.py /usr/local/bin/start-envoy.sh
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -TERM $MAINPID
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
```

Where envoy-hot-restarter.py and start-envoy.sh can found from this doc:
https://www.envoyproxy.io/docs/envoy/latest/operations/hot_restarter

We're trying to simplify this a bit with the package and release with right wrappers.

**Comment by nskalis** [comment]
thanks @lizan looking forward with what you'll come up with :)

could you advise a little bit more please:

```
# ls -salt /usr/local/bin/*envoy*
4 -rwxr-xr-x. 1 envoy envoy  157 Sep 10 10:11 /usr/local/bin/start_envoy.sh
8 -rwxr-xr-x. 1 envoy envoy 6494 Sep 10 09:52 /usr/local/bin/envoy-hot-restarter.py
```

* **/usr/local/bin/start_envoy.sh**
```
#!/bin/bash

ulimit -n 102400
exec /bin/envoy --config-path /etc/envoy.d/envoy.cluster.yaml --restart-epoch $RESTART_EPOCH --service-node xxx
```

* **envoy.service**
```
[Unit]
Description=envoy
Requires=network-online.target
After=network-online.target

[Service]
Type=simple
User=envoy
ExecStartPre=/bin/envoy --mode validate --config-path /etc/envoy.d/envoy.cluster.yaml 
ExecStart=/usr/local/bin/envoy-hot-restarter.py /usr/local/bin/start-envoy.sh
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -TERM $MAINPID
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
```

But, I am getting the following error message:
```
# python2 /usr/local/bin/envoy-hot-restarter.py /usr/local/bin/start-envoy.sh
starting hot-restarter with target: /usr/local/bin/start-envoy.sh
forking and execing new child process at epoch 0
forked new child process with PID=3720
Traceback (most recent call last):
  File "/usr/local/bin/envoy-hot-restarter.py", line 209, in <module>
    main()
  File "/usr/local/bin/envoy-hot-restarter.py", line 203, in main
    fork_and_exec()
  File "/usr/local/bin/envoy-hot-restarter.py", line 182, in fork_and_exec
    os.execl(sys.argv[1], sys.argv[1])
  File "/usr/lib64/python2.7/os.py", line 312, in execl
    execv(file, args)
OSError: [Errno 2] No such file or directory
got SIGCHLD
PID=3720 exited with code=1
Due to abnormal exit, force killing all child processes and exiting
exiting due to lack of child processes
```

**Comment by b-rohit** [comment]
@lizan shouldn't it be as following .

`ExecStart=python3 /usr/local/bin/envoy-hot-restarter.py /usr/local/bin/start-envoy.sh`
